### ISSUE TITLE
Password stores in plain txt, how to solve this?

### ISSUE THREAD

**Issue by kolobok55** [portapps/brave-portable#15]
With notepad++ i've found my site passwords in open view. Can i store my passwords secure?

**Comment by crazy-max** [comment]
@kolobok55 

Everything is explained here :
* https://github.com/portapps/brave-portable/issues/4
* https://github.com/brave/brave-core/pull/795#issue-228093351

TLDR; We have to deal with machine ID and encryption otherwise extensions, passwords and settings are not saved across computers. That's why the flag [`--disable-encryption-win`](https://github.com/brave/brave-core/pull/795/files#diff-a9d2a0787e829b9ff4f75ffff0682354R47) has been created to allow portablility.

**Comment by caspertone2003** [comment]
@crazy-max 

Perhaps it would be wise

a) to include some information on particularities of braveportable vs brave-core in https://portapps.io/app/brave-portable/ , specially the security implications vs portability

b) to point to some side measures, such as https://www.geckoandfly.com/21463/usb-password-protect-lock-encrypt-flash-drive/ 

c) to generate two versions, one as now fully portable and another new safer but not fully portable

Your work here is excellent but users could not really understand the approach and could bring bad reputation to brave-portable, which would be a pity.

a+b are not really a lot of work.
c depends on the level of sofistication of your toolchain....


by the way, I could stop LOLing with you using TLDR

CT

**Comment by crazy-max** [comment]
@caspertone2003 You right I will add some info about those flags.

**Comment by kolobok55** [comment]
> @crazy-max
> 
> Perhaps it would be wise
> 
> a) to include some information on particularities of braveportable vs brave-core in https://portapps.io/app/brave-portable/ , specially the security implications vs portability
> 
> b) to point to some side measures, such as https://www.geckoandfly.com/21463/usb-password-protect-lock-encrypt-flash-drive/
> 
> c) to generate two versions, one as now fully portable and another new safer but not fully portable
> 
> Your work here is excellent but users could not really understand the approach and could bring bad reputation to brave-portable, which would be a pity.
> 
> a+b are not really a lot of work.
> c depends on the level of sofistication of your toolchain....
> 
> by the way, I could stop LOLing with you using TLDR
> 
> CT

Another option, rather a crutch:
Embed a cryptographer / decoder into the launcher, decrypt the settings file on startup and delete on closing

**Comment by crazy-max** [comment]
@kolobok55 That sounds great but this needs an upstream implantation on brave-core and also a portable fingerprint for a simmetric cryptography

**Comment by caspertone2003** [comment]
@kolobok55 
The general approach is good while obvious but not light in work and time.
It took a brilliant idea and quite some work to crazy-max to prepare a patch to brave-core to allow a truly portable solution (Chromium binds passwords and other critical information to a specific machine - by design) and took several weeks to get green light for the patch. Moreover I dunno if they will pass such radical patching as to develop a cryptographic container for brave-core, besides crypto while conceptually simple is a trapfield in terms of correct implementation...

**Comment by crazy-max** [comment]
Done, see https://portapps.io/app/brave-portable/#infos

**Comment by beppe9000** [comment]
Is this still happening?

This issue of portability always bugged me on chromiums... can't brave be patched to just use a default key?

Or a key (or keyfile) could passed by well known file (`%CD%\key.bin`) / argument / pipe / stdin by the wrapper?

**Comment by crazy-max** [comment]
@beppe9000

> Is this still happening?

Yes

> can it be patched to just use a default key?

The steganographic approach is possible to "hide" this kind of data.

**Comment by beppe9000** [comment]
too bad closed source browsers like vivaldi cannot benefit from that patch
