### ISSUE TITLE
yml settings no applying?

### ISSUE THREAD

**Issue by alepodj** [portapps/brave-portable#56]
#### Steps to reproduce this issue

1. Edit brave-portable.yml to add disable_log: true under common
2. App still create the sample.yml and the log folder and collect logs under logs folder

#### Expected behaviour

> Upon deletion the log folder should not be recreated if the flag disable_log: true is set

#### Actual behaviour

> sample.yml gets created every time the app is run even if its renamed to follow https://portapps.io/doc/configuration/

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 1.2.43 release 46

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro 64 bits

**Winver screenshot** : Version 1809 OS Build 17763.1158

### Logs

This is what i need to remove all together, its causing permission issues when i deploy an app that includes brave portable, the .log file under log folder cause the app not to open, i need to be able to open brave without generating logs

**Comment by alepodj** [comment]
Thanks for creating brave-portable i must say :)

That aside, any way to stop brave portable from creating and collecting the log/brave-portable.log file  at all?

**Comment by crazy-max** [comment]
@alepodj,

> Edit brave-portable.yml to add disable_log: true under common
> App release / arch (ex. 1.0.0-2 win64) : 1.2.43 release 46

`disable_log` feature is only available since Portapps 2.0.0 which is for Brave [1.5.123-52](https://github.com/portapps/brave-portable/releases/tag/1.5.123-52).

> App still create the sample.yml

This is the expected behavior, this file is created at each run to allow it to be updated if new entries are available at the time of a new release.

See also https://github.com/portapps/skype-portable/issues/14#issuecomment-589103395 and portapps/portapps#62

> Thanks for creating brave-portable i must say :)

You're welcome!
